// retro sprite mode now points at the curated gen-2-style sprites in
// app/public/gen2-sprites/ (generated by scripts/gen2-sprites/finalize.mjs).
// the previous implementation used pokémon showdown's gen-5 BW CDN — kept
// here in commented form for reference; resurrect if we ever want to mix
// or restore that source.
//
// resolution rules (callers should expect null when the slug isn't curated):
//   getRetroPng(slug)   → '/gen2-sprites/<slug>.png'  if curated, else null
//   getRetroGif(slug)   → '/gen2-sprites/<slug>.gif'  if curated, else null
//   hasRetroSprite(slug)→ true iff a curated png is shipped
//
// callers in retro mode should fall back to pokemon.json's official sprite_url
// when these return null, so uncurated mons still render something visible.

import {
  hasGen2Sprite,
  getGen2Png,
  getGen2Gif,
  getGen2Credit,
} from './gen2-sprite';

export function hasRetroSprite(slug) {
  return hasGen2Sprite(slug || '');
}

export function getRetroPng(slug, { shiny = false } = {}) {
  return getGen2Png(slug || '', { shiny });
}

export function getRetroGif(slug, { shiny = false } = {}) {
  return getGen2Gif(slug || '', { shiny });
}

export function getRetroSprites({ form, species, shiny = false }) {
  const primary = form || species;
  return {
    png: getRetroPng(primary, { shiny }),
    gif: getRetroGif(primary, { shiny }),
    fallbackPng: species && species !== primary ? getRetroPng(species, { shiny }) : null,
    fallbackGif: species && species !== primary ? getRetroGif(species, { shiny }) : null,
  };
}

// kept as a no-op so any leftover callers don't break. the old gen-5 BW
// path needed showdown's slug normalization; gen-2 paths use our pokeapi
// slugs directly.
export function toShowdownSlug(slug) { return slug || ''; }

// per-slug artist credit for the curated retro sprite. follows the same
// form→species fallback as getRetroPng so a non-curated form's card still
// shows the species-level artist credit (since that's the sprite that
// actually rendered). returns null if neither slug is curated.
export function getRetroCredit(slug, speciesSlug = null) {
  const direct = getGen2Credit(slug);
  if (direct) return direct;
  if (speciesSlug && speciesSlug !== slug) return getGen2Credit(speciesSlug);
  return null;
}

// derive a clean display label from a URL — used to give grid-upload /
// manual entries a human-readable source instead of "grid-upload" /
// "manual". 'https://instagram.com/jingstarzx' → 'instagram', etc.
// returns null if the url is missing or unparseable.
export function urlToShortLabel(url) {
  if (!url) return null;
  try {
    const u = new URL(url);
    const host = u.hostname.replace(/^www\./i, '');
    // strip common TLDs so 'deviantart.com' reads as 'deviantart'. multi-
    // part hosts (twitter.com vs api.twitter.com) still produce a sensible
    // short form because we only strip the trailing tld.
    const trimmed = host.replace(/\.(com|net|org|io|co|app|gg)$/i, '');
    return trimmed || host;
  } catch {
    return null;
  }
}

// returns the source label that should appear in the credit byline. for
// "real" sources (pokewilds, crystal, polished-crystal) the source name is
// already meaningful and gets used directly. for internal source markers
// ('grid-upload', 'manual') we derive a clean label from the source url so
// the user sees 'instagram' instead of 'grid-upload'.
export function displaySourceLabel(credit) {
  if (!credit) return null;
  const internal = credit.source === 'grid-upload' || credit.source === 'manual';
  if (internal) return urlToShortLabel(credit.sourceUrl) || urlToShortLabel(credit.creditUrl);
  return credit.source || null;
}

// shortens the verbose attributions some sources ship:
//   - pokewilds: "front = EeVeeEe; back = EeVeeEe; animation = EeVeeEe;
//     overworld = Blumiau; overworldanims = Blumiau" — we only ship the
//     front sprite (+ its animation), so the back/overworld credits are
//     noise. extract the front (and animation if it credits someone
//     different) only.
//   - "X contributors" → "X" (e.g. "PokéWilds contributors" → "PokéWilds").
// applied at render time so existing decisions.json picks get the cleanup
// for free, no re-finalize needed.
export function cleanRetroCredit(raw) {
  if (!raw) return '';
  let s = String(raw).trim();

  // multi-role pokewilds format: split on `;`, keep only `front` (and
  // `animation` when it names a different artist). dedup so the same
  // artist isn't listed twice.
  if (s.includes('=') && /\b(front|back|animation|overworld)\s*=/i.test(s)) {
    const parts = s.split(/\s*;\s*/);
    const get = (role) => {
      const hit = parts.find((p) => new RegExp(`^${role}\\s*=`, 'i').test(p));
      return hit ? hit.replace(new RegExp(`^${role}\\s*=\\s*`, 'i'), '').trim() : null;
    };
    const front = get('front');
    const anim  = get('animation');
    if (front) {
      s = (anim && anim.toLowerCase() !== front.toLowerCase())
        ? `${front} (anim: ${anim})`
        : front;
    }
  }

  // trim trailing "contributors" — keeps the project name as the visible credit
  s = s.replace(/\s+contributors$/i, '');
  return s;
}
